const houseplantdata = {
  tropicals: [
        {
        id: 1,
        name: "Golden Pothos",
        scientificName: "Epipremnum aureum",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Houseplants/pothos.jpg",
        description: "",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Medium Brightness",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/High-water.png",
        waterRequirement: "High Water",
        hardinessZones: '4-9',
        matureSize: `18" x 24"`
        },
        {
        id: 1,
        name: "Peace Lily",
        scientificName: "",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Houseplants/peace-lily-4269363_1280.jpg",
        description: "",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Bright Room",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/High-water.png",
        waterRequirement: "High Water",
        hardinessZones: '4-9',
        matureSize: `18" x 24"`
        },
        {
        id: 1,
        name: "African Violet",
        scientificName: "Saintpaulia lonantha",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Houseplants/african-violet-5054649_1280.jpg",
        description: "",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Partial Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/High-water.png",
        waterRequirement: "High Water",
        hardinessZones: '4-9',
        matureSize: `18" x 24"`
        },
    
        {
        id: 1,
        name: "Spider Plant",
        scientificName: "Chlorophytum Comosum",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Houseplants/spiderplant.jpg",
        description: "",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Partial Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/High-water.png",
        waterRequirement: "High Water",
        hardinessZones: '4-9',
        matureSize: `18" x 24"`
        },
        {
        id: 1,
        name: "Rubber Plant",
        scientificName: "Ficus Elastica",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Houseplants/rubberplant.jpg",
        description: "",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Partial Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/High-water.png",
        waterRequirement: "High Water",
        hardinessZones: '4-9',
        matureSize: `18" x 24"`
        },
        {
        id: 1,
        name: "Monstera Deliciosa",
        scientificName: "Monstera Deliciosa",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Houseplants/Monstera-deliciosa.jpg",
        description: "",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Partial Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/High-water.png",
        waterRequirement: "High Water",
        hardinessZones: '4-9',
        matureSize: `18" x 24"`
        },
        {
        id: 1,
        name: "Umbrella Plant",
        scientificName: "Schefflera Actinophylla",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/TypesofProducts/geranium.jpg",
        description: "",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Partial Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/High-water.png",
        waterRequirement: "High Water",
        hardinessZones: '4-9',
        matureSize: `18" x 24"`
        },
            {
        id: 1,
        name: "Money Tree",
        scientificName: "Guiana Chestnut",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/TypesofProducts/geranium.jpg",
        description: "",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Partial Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/High-water.png",
        waterRequirement: "High Water",
        hardinessZones: '4-9',
        matureSize: `18" x 24"`
        },
            {
        id: 1,
        name: "ZZ Plant",
        scientificName: "Zamioculcas Zamiifolia",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Houseplants/zz-plant.jpg",
        description: "",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Partial Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/High-water.png",
        waterRequirement: "High Water",
        hardinessZones: '4-9',
        matureSize: `18" x 24"`
        },
            {
        id: 1,
        name: "Boston Fern",
        scientificName: "Nephrolepis Exaltata",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Houseplants/boston-fern.jpg",
        description: "",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Partial Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/High-water.png",
        waterRequirement: "High Water",
        hardinessZones: '4-9',
        matureSize: `18" x 24"`
        },
            {
        id: 1,
        name: "Areca Palms",
        scientificName: "Dypsis Lutescens",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Houseplants/areca-palm.jpg",
        description: "",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Partial Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/High-water.png",
        waterRequirement: "High Water",
        hardinessZones: '4-9',
        matureSize: `18" x 24"`
        },
            {
        id: 1,
        name: "Fiddle Leaf Fig",
        scientificName: "Ficus Lyrata",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Houseplants/fiddle-leaf-fig.jpg",
        description: "",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Partial Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/High-water.png",
        waterRequirement: "High Water",
        hardinessZones: '4-9',
        matureSize: `18" x 24"`
        },
            {
        id: 1,
        name: "Pilea",
        scientificName: "Pilea Peperomioides",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Houseplants/pilea-3852265_1280.jpg",
        description: "",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Partial Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/High-water.png",
        waterRequirement: "High Water",
        hardinessZones: '4-9',
        matureSize: `18" x 24"`
        },
            {
        id: 1,
        name: "Bromeliad",
        scientificName: "Bromeliad",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Houseplants/bromeliad-7468152_1280.jpg",
        description: "",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Partial Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/High-water.png",
        waterRequirement: "High Water",
        hardinessZones: '4-9',
        matureSize: `18" x 24"`
        },
            {
        id: 1,
        name: "Dragon Tree",
        scientificName: "Dracaena Marginata",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/TypesofProducts/geranium.jpg",
        description: "",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Partial Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/High-water.png",
        waterRequirement: "High Water",
        hardinessZones: '4-9',
        matureSize: `18" x 24"`
        },
            {
        id: 1,
        name: "String of Pearls",
        scientificName: "Curio Rowleyanus",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Houseplants/string-of-pearls.jpg",
        description: "",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Partial Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/High-water.png",
        waterRequirement: "High Water",
        hardinessZones: '4-9',
        matureSize: `18" x 24"`
        },
            {
        id: 1,
        name: "Croton",
        scientificName: "Coduaeum Variegatum",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Houseplants/croton-8316902_1280.jpg",
        description: "",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Partial Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/High-water.png",
        waterRequirement: "High Water",
        hardinessZones: '4-9',
        matureSize: `18" x 24"`
        },
            {
        id: 1,
        name: "Chinese Evergreen",
        scientificName: "Aglaonema Commutatum",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/TypesofProducts/geranium.jpg",
        description: "",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Partial Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/High-water.png",
        waterRequirement: "High Water",
        hardinessZones: '4-9',
        matureSize: `18" x 24"`
        },
            {
        id: 1,
        name: "Ponytail Palm",
        scientificName: "Beaucarnea Recurvata",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Houseplants/ponytail-palm.jpg",
        description: "",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Partial Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/High-water.png",
        waterRequirement: "High Water",
        hardinessZones: '4-9',
        matureSize: `18" x 24"`
        },
            {
        id: 1,
        name: "Oyster Plant",
        scientificName: "Tradescantia Spathacea",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Houseplants/oyster-plant.jpg",
        description: "",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Partial Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/High-water.png",
        waterRequirement: "High Water",
        hardinessZones: '4-9',
        matureSize: `18" x 24"`
        },
            {
        id: 1,
        name: "Jasmine Plant",
        scientificName: "Jasminum",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Houseplants/jasmin-2779142_1280.jpg",
        description: "",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Partial Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/High-water.png",
        waterRequirement: "High Water",
        hardinessZones: '4-9',
        matureSize: `18" x 24"`
        },
            {
        id: 1,
        name: "Heartleaf Philodendron",
        scientificName: "Philodendron Hederaceum",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Houseplants/heart-leafed-phil.jpg",
        description: "",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Partial Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/High-water.png",
        waterRequirement: "High Water",
        hardinessZones: '4-9',
        matureSize: `18" x 24"`
        },
            {
        id: 1,
        name: "Polka Dot Begonia",
        scientificName: "Begonia Maculata",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Houseplants/polka-dot-begonia.jpg",
        description: "",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Partial Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/High-water.png",
        waterRequirement: "High Water",
        hardinessZones: '4-9',
        matureSize: `18" x 24"`
        },
            {
        id: 1,
        name: "Black Velvet Alocasia",
        scientificName: "Alocasia Reginula",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Houseplants/alocasia-leaf-5911100_1280.jpg",
        description: "",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Partial Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/High-water.png",
        waterRequirement: "High Water",
        hardinessZones: '4-9',
        matureSize: `18" x 24"`
        },
            {
        id: 1,
        name: "Prayer Plant",
        scientificName: "Maranta Leuconeura",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Houseplants/prayer-plant.jpg",
        description: "",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Partial Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/High-water.png",
        waterRequirement: "High Water",
        hardinessZones: '4-9',
        matureSize: `18" x 24"`
        },
            {
        id: 1,
        name: "Fan Palm",
        scientificName: "Maranta Leuconeura",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/TypesofProducts/geranium.jpg",
        description: "",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Partial Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/High-water.png",
        waterRequirement: "High Water",
        hardinessZones: '4-9',
        matureSize: `18" x 24"`
        },
            {
        id: 1,
        name: "Lemon Tree",
        scientificName: "Maranta Leuconeura",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Houseplants/lemons-4533375_1280.jpg",
        description: "",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Partial Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/High-water.png",
        waterRequirement: "High Water",
        hardinessZones: '4-9',
        matureSize: `18" x 24"`
        },
            {
        id: 1,
        name: "Parlor Palm",
        scientificName: "Maranta Leuconeura",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/TypesofProducts/geranium.jpg",
        description: "",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Partial Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/High-water.png",
        waterRequirement: "High Water",
        hardinessZones: '4-9',
        matureSize: `18" x 24"`
        },
        {
        id: 1,
        name: "Orchid",
        scientificName: "Maranta Leuconeura",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Houseplants/orchids-1528330_1280.jpg",
        description: "",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Partial Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/High-water.png",
        waterRequirement: "High Water",
        hardinessZones: '4-9',
        matureSize: `18" x 24"`
        },

     
  ],
  succulenets: [
            {
        id: 1,
        name: "Kalanchoe",
        scientificName: "Pelargonium spp.",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Houseplants/flaming-kathchen-189547_1280.jpg",
        description: "",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Partial Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/High-water.png",
        waterRequirement: "High Water",
        hardinessZones: '4-9',
        matureSize: `18" x 24"`
        },
            {
        id: 1,
        name: "Jade Plant",
        scientificName: "Crassula Ovata",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Houseplants/jade-plant-1633676_1280.jpg",
        description: "",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Partial Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/High-water.png",
        waterRequirement: "High Water",
        hardinessZones: '4-9',
        matureSize: `18" x 24"`
        },
            {
        id: 1,
        name: "Zebra Plant",
        scientificName: "Crassula Ovata",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Houseplants/zebra-plant.jpg",
        description: "",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Partial Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/High-water.png",
        waterRequirement: "High Water",
        hardinessZones: '4-9',
        matureSize: `18" x 24"`
        },
            {
        id: 1,
        name: "Wooly Crassula",
        scientificName: "Crassula Ovata",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/TypesofProducts/geranium.jpg",
        description: "",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Partial Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/High-water.png",
        waterRequirement: "High Water",
        hardinessZones: '4-9',
        matureSize: `18" x 24"`
        },
            {
        id: 1,
        name: "Ivory Pagoda",
        scientificName: "Crassula Ovata",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/TypesofProducts/geranium.jpg",
        description: "",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Partial Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/High-water.png",
        waterRequirement: "High Water",
        hardinessZones: '4-9',
        matureSize: `18" x 24"`
        },
            {
        id: 1,
        name: "Weeping Fig Ficus",
        scientificName: "Crassula Ovata",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Houseplants/weeping-fig-ficus.jpg",
        description: "",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Partial Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/High-water.png",
        waterRequirement: "High Water",
        hardinessZones: '4-9',
        matureSize: `18" x 24"`
        },
            {
        id: 1,
        name: "Wandering Jew",
        scientificName: "Crassula Ovata",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Houseplants/wandering-jew.jpg",
        description: "",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Partial Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/High-water.png",
        waterRequirement: "High Water",
        hardinessZones: '4-9',
        matureSize: `18" x 24"`
        },
            {
        id: 1,
        name: "Bamboo Palm",
        scientificName: "Crassula Ovata",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/TypesofProducts/geranium.jpg",
        description: "",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Partial Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/High-water.png",
        waterRequirement: "High Water",
        hardinessZones: '4-9',
        matureSize: `18" x 24"`
        },
            {
        id: 1,
        name: "Cat Palm",
        scientificName: "Crassula Ovata",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/TypesofProducts/geranium.jpg",
        description: "",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Partial Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/High-water.png",
        waterRequirement: "High Water",
        hardinessZones: '4-9',
        matureSize: `18" x 24"`
        },
            {
        id: 1,
        name: "Ficus Tineke",
        scientificName: "Crassula Ovata",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/TypesofProducts/geranium.jpg",
        description: "",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Partial Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/High-water.png",
        waterRequirement: "High Water",
        hardinessZones: '4-9',
        matureSize: `18" x 24"`
        },
            {
        id: 1,
        name: "red-anthurium",
        scientificName: "Crassula Ovata",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/TypesofProducts/geranium.jpg",
        description: "",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Partial Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/High-water.png",
        waterRequirement: "High Water",
        hardinessZones: '4-9',
        matureSize: `18" x 24"`
        },
            {
        id: 1,
        name: "Snake Plant",
        scientificName: "Crassula Ovata",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/TypesofProducts/geranium.jpg",
        description: "",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Partial Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/High-water.png",
        waterRequirement: "High Water",
        hardinessZones: '4-9',
        matureSize: `18" x 24"`
        },
            {
        id: 1,
        name: "Draceana Marginata",
        scientificName: "Crassula Ovata",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/TypesofProducts/geranium.jpg",
        description: "",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Partial Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/High-water.png",
        waterRequirement: "High Water",
        hardinessZones: '4-9',
        matureSize: `18" x 24"`
        },
            {
        id: 1,
        name: "Kangaroo Fern",
        scientificName: "Crassula Ovata",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/TypesofProducts/geranium.jpg",
        description: "",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Partial Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/High-water.png",
        waterRequirement: "High Water",
        hardinessZones: '4-9',
        matureSize: `18" x 24"`
        },
            {
        id: 1,
        name: "Dracaena Golden Heart",
        scientificName: "Crassula Ovata",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/TypesofProducts/geranium.jpg",
        description: "",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Partial Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/High-water.png",
        waterRequirement: "High Water",
        hardinessZones: '4-9',
        matureSize: `18" x 24"`
        },
  ]
}
export default houseplantdata;
