const houseplantdata = {
  tropicals: [
        {
        id: 1,
        name: "Golden Pothos",
        scientificName: "Epipremnum aureum",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/TypesofProducts/geranium.jpg",
        description: "",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Partial Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/High-water.png",
        waterRequirement: "High Water",
        hardinessZones: '4-9',
        matureSize: `18" x 24"`
        },
        {
        id: 1,
        name: "Peace Lily",
        scientificName: "",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/TypesofProducts/geranium.jpg",
        description: "",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Partial Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/High-water.png",
        waterRequirement: "High Water",
        hardinessZones: '4-9',
        matureSize: `18" x 24"`
        },
        {
        id: 1,
        name: "African Violet",
        scientificName: "Saintpaulia lonantha",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/TypesofProducts/geranium.jpg",
        description: "",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Partial Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/High-water.png",
        waterRequirement: "High Water",
        hardinessZones: '4-9',
        matureSize: `18" x 24"`
        },
    
        {
        id: 1,
        name: "Spider Plant",
        scientificName: "Chlorophytum Comosum",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/TypesofProducts/geranium.jpg",
        description: "",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Partial Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/High-water.png",
        waterRequirement: "High Water",
        hardinessZones: '4-9',
        matureSize: `18" x 24"`
        },
        {
        id: 1,
        name: "Rubber Plant",
        scientificName: "Ficus Elastica",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/TypesofProducts/geranium.jpg",
        description: "",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Partial Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/High-water.png",
        waterRequirement: "High Water",
        hardinessZones: '4-9',
        matureSize: `18" x 24"`
        },
        {
        id: 1,
        name: "Monstera Deliciosa",
        scientificName: "Monstera Deliciosa",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/TypesofProducts/geranium.jpg",
        description: "",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Partial Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/High-water.png",
        waterRequirement: "High Water",
        hardinessZones: '4-9',
        matureSize: `18" x 24"`
        },
        {
        id: 1,
        name: "Umbrella Plant",
        scientificName: "Schefflera Actinophylla",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/TypesofProducts/geranium.jpg",
        description: "",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Partial Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/High-water.png",
        waterRequirement: "High Water",
        hardinessZones: '4-9',
        matureSize: `18" x 24"`
        },
            {
        id: 1,
        name: "Money Tree",
        scientificName: "Guiana Chestnut",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/TypesofProducts/geranium.jpg",
        description: "",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Partial Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/High-water.png",
        waterRequirement: "High Water",
        hardinessZones: '4-9',
        matureSize: `18" x 24"`
        },
            {
        id: 1,
        name: "ZZ Plant",
        scientificName: "Zamioculcas Zamiifolia",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/TypesofProducts/geranium.jpg",
        description: "",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Partial Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/High-water.png",
        waterRequirement: "High Water",
        hardinessZones: '4-9',
        matureSize: `18" x 24"`
        },
            {
        id: 1,
        name: "Boston Fern",
        scientificName: "Nephrolepis Exaltata",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/TypesofProducts/geranium.jpg",
        description: "",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Partial Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/High-water.png",
        waterRequirement: "High Water",
        hardinessZones: '4-9',
        matureSize: `18" x 24"`
        },
            {
        id: 1,
        name: "Areca Palms",
        scientificName: "Dypsis Lutescens",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/TypesofProducts/geranium.jpg",
        description: "",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Partial Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/High-water.png",
        waterRequirement: "High Water",
        hardinessZones: '4-9',
        matureSize: `18" x 24"`
        },
            {
        id: 1,
        name: "Fiddle Leaf Fig",
        scientificName: "Ficus Lyrata",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/TypesofProducts/geranium.jpg",
        description: "",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Partial Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/High-water.png",
        waterRequirement: "High Water",
        hardinessZones: '4-9',
        matureSize: `18" x 24"`
        },
            {
        id: 1,
        name: "Pilea",
        scientificName: "Pilea Peperomioides",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/TypesofProducts/geranium.jpg",
        description: "",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Partial Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/High-water.png",
        waterRequirement: "High Water",
        hardinessZones: '4-9',
        matureSize: `18" x 24"`
        },
            {
        id: 1,
        name: "Bromeliad",
        scientificName: "Bromeliad",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/TypesofProducts/geranium.jpg",
        description: "",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Partial Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/High-water.png",
        waterRequirement: "High Water",
        hardinessZones: '4-9',
        matureSize: `18" x 24"`
        },
            {
        id: 1,
        name: "Dragon Tree",
        scientificName: "Dracaena Marginata",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/TypesofProducts/geranium.jpg",
        description: "",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Partial Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/High-water.png",
        waterRequirement: "High Water",
        hardinessZones: '4-9',
        matureSize: `18" x 24"`
        },
            {
        id: 1,
        name: "String of Pearls",
        scientificName: "Curio Rowleyanus",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/TypesofProducts/geranium.jpg",
        description: "",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Partial Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/High-water.png",
        waterRequirement: "High Water",
        hardinessZones: '4-9',
        matureSize: `18" x 24"`
        },
            {
        id: 1,
        name: "Croton",
        scientificName: "Coduaeum Variegatum",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/TypesofProducts/geranium.jpg",
        description: "",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Partial Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/High-water.png",
        waterRequirement: "High Water",
        hardinessZones: '4-9',
        matureSize: `18" x 24"`
        },
            {
        id: 1,
        name: "Chinese Evergreen",
        scientificName: "Aglaonema Commutatum",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/TypesofProducts/geranium.jpg",
        description: "",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Partial Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/High-water.png",
        waterRequirement: "High Water",
        hardinessZones: '4-9',
        matureSize: `18" x 24"`
        },
            {
        id: 1,
        name: "Ponytail Palm",
        scientificName: "Beaucarnea Recurvata",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/TypesofProducts/geranium.jpg",
        description: "",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Partial Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/High-water.png",
        waterRequirement: "High Water",
        hardinessZones: '4-9',
        matureSize: `18" x 24"`
        },
            {
        id: 1,
        name: "Oyster Plant",
        scientificName: "Tradescantia Spathacea",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/TypesofProducts/geranium.jpg",
        description: "",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Partial Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/High-water.png",
        waterRequirement: "High Water",
        hardinessZones: '4-9',
        matureSize: `18" x 24"`
        },
            {
        id: 1,
        name: "Jasmine Plant",
        scientificName: "Jasminum",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/TypesofProducts/geranium.jpg",
        description: "",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Partial Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/High-water.png",
        waterRequirement: "High Water",
        hardinessZones: '4-9',
        matureSize: `18" x 24"`
        },
            {
        id: 1,
        name: "Heartleaf Philodendron",
        scientificName: "Philodendron Hederaceum",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/TypesofProducts/geranium.jpg",
        description: "",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Partial Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/High-water.png",
        waterRequirement: "High Water",
        hardinessZones: '4-9',
        matureSize: `18" x 24"`
        },
            {
        id: 1,
        name: "Polka Dot Begonia",
        scientificName: "Begonia Maculata",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/TypesofProducts/geranium.jpg",
        description: "",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Partial Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/High-water.png",
        waterRequirement: "High Water",
        hardinessZones: '4-9',
        matureSize: `18" x 24"`
        },
            {
        id: 1,
        name: "Black Velvet Alocasia",
        scientificName: "Alocasia Reginula",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/TypesofProducts/geranium.jpg",
        description: "",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Partial Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/High-water.png",
        waterRequirement: "High Water",
        hardinessZones: '4-9',
        matureSize: `18" x 24"`
        },
            {
        id: 1,
        name: "Prayer Plant",
        scientificName: "Maranta Leuconeura",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/TypesofProducts/geranium.jpg",
        description: "",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Partial Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/High-water.png",
        waterRequirement: "High Water",
        hardinessZones: '4-9',
        matureSize: `18" x 24"`
        },

     
  ],
  succulenet: [
            {
        id: 1,
        name: "Kalanchoe",
        scientificName: "Pelargonium spp.",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/TypesofProducts/geranium.jpg",
        description: "",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Partial Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/High-water.png",
        waterRequirement: "High Water",
        hardinessZones: '4-9',
        matureSize: `18" x 24"`
        },
            {
        id: 1,
        name: "Jade Plant",
        scientificName: "Crassula Ovata",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/TypesofProducts/geranium.jpg",
        description: "",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Partial Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/High-water.png",
        waterRequirement: "High Water",
        hardinessZones: '4-9',
        matureSize: `18" x 24"`
        },
            {
        id: 1,
        name: "Zebra Plant",
        scientificName: "Crassula Ovata",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/TypesofProducts/geranium.jpg",
        description: "",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Partial Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/High-water.png",
        waterRequirement: "High Water",
        hardinessZones: '4-9',
        matureSize: `18" x 24"`
        },
            {
        id: 1,
        name: "Wooly Crassula",
        scientificName: "Crassula Ovata",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/TypesofProducts/geranium.jpg",
        description: "",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Partial Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/High-water.png",
        waterRequirement: "High Water",
        hardinessZones: '4-9',
        matureSize: `18" x 24"`
        },
            {
        id: 1,
        name: "Ivory Pagoda",
        scientificName: "Crassula Ovata",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/TypesofProducts/geranium.jpg",
        description: "",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Partial Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/High-water.png",
        waterRequirement: "High Water",
        hardinessZones: '4-9',
        matureSize: `18" x 24"`
        },
            {
        id: 1,
        name: "Jade Plant",
        scientificName: "Crassula Ovata",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/TypesofProducts/geranium.jpg",
        description: "",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Partial Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/High-water.png",
        waterRequirement: "High Water",
        hardinessZones: '4-9',
        matureSize: `18" x 24"`
        },
            {
        id: 1,
        name: "Jade Plant",
        scientificName: "Crassula Ovata",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/TypesofProducts/geranium.jpg",
        description: "",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Partial Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/High-water.png",
        waterRequirement: "High Water",
        hardinessZones: '4-9',
        matureSize: `18" x 24"`
        },
  ]
}