const houseplantdata = {
  tropicals: [
        {
        id: 1,
        name: "Golden Pothos",
        scientificName: "Epipremnum aureum",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Houseplants/pothos.jpg",
        description: "Golden Pothos is an amazing trailing houseplant, known for its heart-shaped, variegated leaves and effortless care. Thriving in low light and happy with minimal attention, it’s perfect for adding a pop of green to any room—and a favorite at Jericho Nursery.",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Cloudy.png",
            sunRequirement: "Low Light",
         waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
            waterRequirement: "Low Water",
        hardinessZones: "10-12",
        matureSize: `6' x 6'`
        },
        {
        id: 1,
        name: "Spider Plant",
        scientificName: "Chlorophytum Comosum",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Houseplants/spiderplant.jpg",
        description: "Few houseplants are as cheerful and adaptable as the Spider Plant. Its striped leaves and arching stems make it ideal for hanging baskets, and it thrives in a wide range of indoor conditions with very little fuss.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Medium Brightness",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Medium-water.png",
        waterRequirement: "Medium Water",
        hardinessZones: '9-11',
        matureSize: `12" x 24"`
        },
        {
        id: 1,
        name: "Rubber Plant",
        scientificName: "Ficus Elastica",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Houseplants/rubberplant.jpg",
        description: "With its broad, glossy leaves and bold presence, the Rubber Plant adds instant drama to any indoor space. It thrives in bright, indirect light and is incredibly low-maintenance, making it a striking and reliable choice for modern homes.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Medium Brightness",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Medium-water.png",
        waterRequirement: "Medium Water",
        hardinessZones: '10-12',
        matureSize: `6'-10'`
        },
        {
        id: 1,
        name: "Monstera Deliciosa",
        scientificName: "Monstera Deliciosa",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Houseplants/Monstera-deliciosa.jpg",
        description: "A must-have for plant lovers, Monstera Deliciosa offers iconic split leaves that add instant tropical style. It grows quickly with the right light and makes a stunning statement in living rooms, offices, or sunrooms.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Medium Brightness",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Medium-water.png",
        waterRequirement: "Medium Water",
        hardinessZones: '10-12',
        matureSize: `6' x 3'`
        },
        {
        id: 1,
        name: "Umbrella Plant",
        scientificName: "Schefflera Actinophylla",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Houseplants/schefflera.jpg",
        description: "The Umbrella Plant, or Schefflera, brings height and elegance to indoor spaces with its glossy, umbrella-like leaf clusters. Low-maintenance and fast-growing, it’s a great choice for bright rooms and a longtime favorite among Jericho Nursery customers.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Medium Brightness",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Medium-water.png",
        waterRequirement: "Medium Water",
        hardinessZones: "10-12",
        matureSize: `7' x 3'`
        },
            {
        id: 1,
        name: "Money Tree",
        scientificName: "Guiana Chestnut",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Houseplants/money-tree.jpg",
        description: "The Money Tree is a symbol of good fortune and a stylish addition to any home or office. With its braided trunk and shiny green leaves, it thrives in bright, indirect light and adds a touch of tropical charm with minimal upkeep.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Medium Brightness",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Medium-water.png",
        waterRequirement: "Medium Water",
        hardinessZones: "10-12",
        matureSize: `4' x 2'`
        },
            {
        id: 1,
        name: "ZZ Plant",
        scientificName: "Zamioculcas Zamiifolia",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Houseplants/zz-plant.jpg",
        description: "Tough, glossy, and almost impossible to kill, the ZZ Plant is a top pick for low-light spaces and busy plant owners. Its deep green leaves add a sleek, modern look—perfect for homes or offices needing a low-maintenance touch of green.",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Cloudy.png",
            sunRequirement: "Low Light",
         waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
            waterRequirement: "Low Water",
        hardinessZones: "10-12",
        matureSize: `3' x 2'`
        },
            {
        id: 1,
        name: "Boston Fern",
        scientificName: "Nephrolepis Exaltata",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Houseplants/boston-fern.jpg",
        description: "Lush and full of texture, the Boston Fern brings classic charm to any indoor setting. It loves humidity and indirect light, making it ideal for bathrooms, kitchens, or shaded patios around New Mexico.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Medium Brightness",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/High-water.png",
            waterRequirement: "High Water",
          hardinessZones: "10-12",
          matureSize: `2' x 3'`
        },
            {
        id: 1,
        name: "Areca Palm",
        scientificName: "Dypsis Lutescens",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Houseplants/areca-palm2.jpg",
        description: "The Areca Palm delivers graceful, arching fronds that instantly create a tropical feel indoors. As one of Jericho Nursery’s most elegant houseplants, it purifies the air and flourishes in bright, indirect light with regular watering.",
      sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Medium Brightness",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Medium-water.png",
        waterRequirement: "Medium Water",
        hardinessZones: "10-12",
        matureSize: `6' x 6'`
        },
            {
        id: 1,
        name: "Fiddle Leaf Fig",
        scientificName: "Ficus Lyrata",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Houseplants/fiddle-leaf-fig.jpg",
        description: "Known for its large, violin-shaped leaves, the Fiddle Leaf Fig makes a bold, sculptural statement in any well-lit room. It’s a favorite for modern interiors and thrives with a consistent care routine and bright, indirect light.",
      sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Medium Brightness",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Medium-water.png",
        waterRequirement: "Medium Water",
        hardinessZones: "10-12",
        matureSize: `6' x 3'`
        },
            {
        id: 1,
        name: "Chinese Money Plant",
        scientificName: "Pilea Peperomioides",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Houseplants/pilea-3852265_1280.jpg",
        description: "Compact and playful, the Chinese Money Plant features round, coin-like leaves on upright stems. It’s easy to grow, loves bright light, and adds a quirky, eye-catching accent to desks, shelves, or windowsills.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Medium Brightness",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Medium-water.png",
        waterRequirement: "Medium Water",
        hardinessZones: "10-12",
        matureSize: `1' x 1'`
        },
            {
        id: 1,
        name: "Bromeliad",
        scientificName: "Bromeliaceae",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Houseplants/bromeliad-7468152_1280.jpg",
        description: "With vibrant, tropical blooms and striking foliage, Bromeliads are a colorful way to liven up indoor spaces. These low-maintenance beauties thrive in bright, filtered light and are a standout at Jericho Nursery for their unique style and flair.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Medium Brightness",
         waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
            waterRequirement: "Low Water",
        hardinessZones: "10-12",
        matureSize: `1' x 1'`
        },
  

            {
        id: 1,
        name: "Croton",
        scientificName: "Coduaeum Variegatum",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Houseplants/croton-8316902_1280.jpg",
        description: "Croton is a showstopper with bold, multicolored leaves in shades of red, orange, yellow, and green. It loves bright light to keep its colors vibrant and adds a splash of tropical energy to any indoor plant collection.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Medium Brightness",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Medium-water.png",
        waterRequirement: "Medium Water",
        hardinessZones: "10-12",
        matureSize: `5' x 3'`
        },
            {
        id: 1,
        name: "Chinese Evergreen",
        scientificName: "Aglaonema Commutatum",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Houseplants/Aglaonema.jpg",
        description: "The Chinese Evergreen is a reliable favorite, valued for its striking patterned leaves and ability to thrive in low light. It's one of the easiest houseplants to care for, making it perfect for both beginners and seasoned plant lovers.",
             sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Cloudy.png",
            sunRequirement: "Low Light",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Medium-water.png",
        waterRequirement: "Medium Water",
        hardinessZones: "10-12",
        matureSize: `2' x 2'`
        },
            {
        id: 1,
        name: "Ponytail Palm",
        scientificName: "Beaucarnea Recurvata",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Houseplants/ponytail-plant-1733084_1280.jpg",
        description: "Despite its name, the Ponytail Palm is actually a succulent—and one of the most low-maintenance houseplants around. With its swollen base and flowing, hair-like leaves, it adds a playful, sculptural touch to any bright corner.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Medium Brightness",
         waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
            waterRequirement: "Low Water",
        hardinessZones: "10-12",
        matureSize: `3' x 2'`
        },
            {
        id: 1,
        name: "Oyster Plant",
        scientificName: "Tradescantia Spathacea",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Houseplants/oyster-plant.jpg",
        description: "Compact and colorful, the Oyster Plant features purple-backed leaves that fan out in dramatic rosettes. It's great for small spaces, easy to care for, and a popular pick at Jericho Nursery for adding bold color indoors.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Medium Brightness",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Medium-water.png",
        waterRequirement: "Medium Water",
        hardinessZones: "10-12",
        matureSize: `1' x 2'`
        },
    
            {
        id: 1,
        name: "Heartleaf Philodendron",
        scientificName: "Philodendron Hederaceum",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Houseplants/heart-leafed-phil.jpg",
        description: "Graceful and easygoing, the Heart Leaf Philodendron trails beautifully from shelves or hanging baskets. Its deep green, heart-shaped leaves thrive in low to medium light, making it a timeless classic for indoor greenery.",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Cloudy.png",
            sunRequirement: "Low Light",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Medium-water.png",
        waterRequirement: "Medium Water",
        hardinessZones: "10-12",
        matureSize: `3' x 3'`
        },
     
            {
        id: 1,
        name: "Black Velvet Alocasia",
        scientificName: "Alocasia Reginula",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Houseplants/alocasia-leaf-5911100_1280.jpg",
        description: "Striking and dramatic, Black Velvet Alocasia features rich, dark leaves with silvery veins and a soft, velvety texture. It prefers high humidity and indirect light, making it a prized addition for collectors and a standout at Jericho Nursery.",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Cloudy.png",
            sunRequirement: "Low Light",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Medium-water.png",
        waterRequirement: "Medium Water",
        hardinessZones: "10-12",
        matureSize: `1' x 1'`
        },
            {
        id: 1,
        name: "Prayer Plant",
        scientificName: "Maranta Leuconeura",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Houseplants/prayer-plant.jpg",
        description: "The Prayer Plant is known for its fascinating leaf movement—folding up at night like hands in prayer. With its vibrant patterns and love for humidity, it brings both color and curiosity to any well-lit indoor space.",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Cloudy.png",
            sunRequirement: "Low Light",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Medium-water.png",
        waterRequirement: "Medium Water",
        hardinessZones: "10-12",
        matureSize: `1' x 2'`
        },
  
            {
        id: 1,
        name: "Parlor Palm",
        scientificName: "Chamaedorea elegans",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Houseplants/parlor%20palm.jpg",
        description: "Elegant and adaptable, the Parlor Palm has been a beloved indoor plant for generations. Its feathery fronds thrive in low light and cooler temperatures, making it an easy choice for brightening up any room.",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Cloudy.png",
            sunRequirement: "Low Light",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Medium-water.png",
        waterRequirement: "Medium Water",
        hardinessZones: "10-12",
        matureSize: `4' x 3'`
        },

                    {
        id: 1,
        name: "Ficus (Weeping Fig)",
        scientificName: "Ficus benjamina",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Houseplants/weeping-fig.jpg",
        description: "The Weeping Fig offers classic elegance with its slender branches and glossy green leaves. It thrives in bright, indirect light and brings a refined, tree-like presence to homes and offices alike.",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Medium Brightness",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Medium-water.png",
        waterRequirement: "Medium Water",
        hardinessZones: "10-12",
        matureSize: `6' x 4'`
        },
            {
        id: 1,
        name: "Inchplant",
        scientificName: "Tradescantia zebrina",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Houseplants/wandering-jew.jpg",
        description: "Vibrant and fast-growing, the Wandering Jew features striking purple and silver-striped leaves that trail beautifully. It’s an easy-care plant that loves bright light and adds a bold splash of color to shelves or hanging baskets.",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Medium Brightness",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Medium-water.png",
        waterRequirement: "Medium Water",
      hardinessZones: "10-12",
      matureSize: `1' x 3'`
        },
            {
        id: 1,
        name: "Dragon Plant",
        scientificName: "Draceana Marginata",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Houseplants/draceana.jpg",
        description: "Tall and spiky with deep green leaves edged in red, the Dragon Plant brings a modern, architectural vibe to indoor spaces. Low-maintenance and drought-tolerant, it’s a standout for busy plant lovers and a popular pick at Jericho Nursery.",
             sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Medium Brightness",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
            waterRequirement: "Low Water",
        hardinessZones: "10-12",
        matureSize: `6' x 3'`
        },
  
     
  ],

  flowering: [
         {
        id: 1,
        name: "Peace Lily",
        scientificName: "Spathiphyllum wallisii",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Houseplants/peace-lily-4269363_1280.jpg",
        description: "The Peace Lily is a timeless favorite, known for its graceful white blooms and air-purifying qualities. It thrives in low to medium light and adds a calming, elegant touch to any indoor setting.",
             sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Cloudy.png",
            sunRequirement: "Low Light",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Medium-water.png",
        waterRequirement: "Medium Water",
        hardinessZones: "10-12",
        matureSize: `2' x 3'`
        },
              {
        id: 1,
        name: "Moth Orchid",
        scientificName: "Phalaenopsis",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Houseplants/orchids-1528330_1280.jpg",
        description: "Elegant and exotic, Orchids bring long-lasting blooms in a wide range of colors. They thrive in bright, indirect light with minimal watering, making them a sophisticated favorite for indoor plant lovers.",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Medium Brightness",
         waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
            waterRequirement: "Low Water",
        hardinessZones: "10-12",
        matureSize: `1' x 1'`
        },

              {
        id: 1,
        name: "African Violet",
        scientificName: "Saintpaulia ionantha",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Houseplants/african-violet-5054649_1280.jpg",
        description: "Compact and colorful, African Violets are beloved for their velvety leaves and clusters of purple, pink, or white flowers. They bloom year-round with the right care and are perfect for bright windowsills or small spaces. Make sure to water these beauties from the bottom of the pot, its what they love.",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Cloudy.png",
            sunRequirement: "Low Light",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Medium-water.png",
        waterRequirement: "Medium Water",
        hardinessZones: "10-12",
        matureSize: `0.5' x 0.5'`
        },
                {
        id: 1,
        name: "Jasmine Plant",
        scientificName: "Jasminum",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Houseplants/jasmin-2779142_1280.jpg",
        description: "Known for its sweet, intoxicating scent, the Jasmine Plant fills indoor spaces with fragrance when in bloom. It loves bright light and regular watering, and it’s a top pick at Jericho Nursery for those seeking a flowering houseplant with charm.",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Medium Brightness",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Medium-water.png",
        waterRequirement: "Medium Water",
        hardinessZones: "10-12",
        matureSize: `6' x 4'`
        },
               {
        id: 1,
        name: "Polka Dot Begonia",
        scientificName: "Begonia Maculata",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Houseplants/polka-dot-begonia.jpg",
        description: "The Polka Dot Begonia turns heads with its dramatic spotted leaves and deep red undersides. This striking plant loves bright, indirect light and adds a bold, artistic flair to any indoor plant collection.",
           sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Medium Brightness",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Medium-water.png",
        waterRequirement: "Medium Water",
       hardinessZones: "10-12",
        matureSize: `2' x 2'`
        },
                {
        id: 1,
        name: "Flamingo Flower",
        scientificName: "Anthurium sp.",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Houseplants/anthurium-andreaum-49326_1280.jpg",
        description: "With its glossy heart-shaped leaves and bright red or pink blooms, the Flamingo Flower adds a bold splash of color indoors. It prefers humidity and indirect light, making it a vibrant choice for kitchens or bathrooms.",
             sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Cloudy.png",
            sunRequirement: "Low Light",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Medium-water.png",
        waterRequirement: "Medium Water",
        hardinessZones: "10-12",
        matureSize: `1' x 2'`
        },
              
            {
        id: 1,
        name: "Lemon Tree",
        scientificName: "Citrus limon",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Houseplants/lemons-4533375_1280.jpg",
        description: "Perfect for a sunny window or patio, the Lemon Tree brings fresh fragrance, glossy green foliage, and—yes—real lemons! A customer favorite at Jericho Nursery, it offers beauty and function for indoor gardeners who want a taste of the orchard at home.",
     sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Bright Room",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Medium-water.png",
        waterRequirement: "Medium Water",
          hardinessZones: "9-11",
          matureSize: `10' x 8'`
        },
  ],
  succulenets: [
         
            {
        id: 1,
        name: "Jade Plant",
        scientificName: "Crassula Ovata",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Houseplants/jade-plant-1633676_1280.jpg",
        description: "A symbol of good luck and prosperity, the Jade Plant is a classic succulent with thick, glossy leaves. It stores water in its fleshy stems and leaves, making it a resilient choice for busy plant owners.",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Medium Brightness",
         waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
            waterRequirement: "Low Water",
          hardinessZones: "10-12",
          matureSize: `3' x 3'`
        },
            {
        id: 1,
        name: "Snake Plant",
        scientificName: "Sansevieria",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Houseplants/sansevieria-7385720_1280.jpg",
        description: "Nearly indestructible and strikingly upright, the Snake Plant is ideal for low-light areas and beginner plant owners. Its bold, sword-like leaves also help purify the air, making it both functional and beautiful.",
             sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Cloudy.png",
            sunRequirement: "Low Light",
         waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
            waterRequirement: "Low Water",
        hardinessZones: "10-12",
        matureSize: `3' x 1.5'`
        },
           {
        id: 1,
        name: "String of Pearls",
        scientificName: "Senecio rowleyanus",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Houseplants/string-of-pearls.jpg",
        description: "Unique and eye-catching, String of Pearls trails with bead-like leaves that add a whimsical touch to shelves and hanging pots. It thrives in bright light and is a favorite at Jericho Nursery for its playful charm.",
         sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Medium Brightness",
         waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
            waterRequirement: "Low Water",
        hardinessZones: "10-12",
        matureSize: `1' x 2'`
        },
           {
        id: 1,
        name: "Echerveria",
        scientificName: "Echeveria elegans",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Houseplants/echeveria.jpg",
        description: "Echeveria is a colorful, rosette-shaped succulent that thrives in bright light and dry conditions. Its compact form and low-maintenance nature make it a popular pick at Jericho Nursery for windowsills and small spaces.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Bright Room",
         waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
            waterRequirement: "Low Water",
          hardinessZones: "10-12",
          matureSize: `1' x 1'`
        },
           {
        id: 1,
        name: "Aloe Vera",
        scientificName: "Aloe barbadensis miller",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Houseplants/aloe-vera-2623317_1280.jpg",
        description: "Aloe Vera is a sun-loving succulent known for its spiky green leaves filled with soothing gel. Perfect for bright windowsills, it’s both functional and attractive—easy to care for and drought-tolerant. A longtime favorite at Jericho Nursery for its healing properties and architectural form.",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Bright Room",
         waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
            waterRequirement: "Low Water",
          hardinessZones: "10-12",
          matureSize: `2' x 2'`
        },
           {
        id: 1,
        name: "Zerba Plant",
        scientificName: "Haworthia",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Houseplants/zerba-plant.jpg",
        description: "Compact and low-maintenance, the Zebra Plant stands out with its striking white stripes and spiky green leaves. Ideal for desks, shelves, or small pots, it thrives in bright, indirect light and requires very little water. A great choice for beginners and a popular pick at Jericho Nursery.",
         sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Medium Brightness",
         waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
            waterRequirement: "Low Water",
          hardinessZones: "10-12",
          matureSize: `1' x 1'`
        },
           {
        id: 1,
        name: "Burro's Tail",
        scientificName: "Sedum morganianum",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Houseplants/burro's-tail.jpg",
        description: "Burro’s Tail is a trailing succulent with plump, blue-green leaves that cascade gracefully, making it perfect for hanging baskets and high shelves. A favorite at Jericho Nursery, it thrives in bright light and needs minimal watering.",
         sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Medium Brightness",
         waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
            waterRequirement: "Low Water",
        hardinessZones: "10-12",
        matureSize: `1' x 2'`
        },
           {
        id: 1,
        name: "Kalanchoe",
        scientificName: "Kalanchoe blossfeldiana",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Houseplants/flaming-kathchen-189547_1280.jpg",
        description: "Bursting with clusters of vibrant blooms, Kalanchoe is a cheerful succulent that brings long-lasting color indoors. It’s low-maintenance, drought-tolerant, and thrives in bright light—perfect for sunny windowsills.",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Medium Brightness",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Medium-water.png",
        waterRequirement: "Medium Water",
        hardinessZones: "10-12",
        matureSize: `1.5' x 1.5'`
        },
  ]
}
export default houseplantdata;
