const perennialdata = {
  bedding: [
    {
      id: 1,
      name: "Red Valerian",
      scientificName: "Centranthus ruber",
      image:
        "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/perennials/red_valerian.jpg",
      description:
        "Red Valerian, or Centranthus ruber, is a vibrant, drought-tolerant perennial that thrives in New Mexico’s dry, sunny conditions. Its clusters of bright red, pink, or white flowers bloom from late spring to summer, attracting pollinators like bees and butterflies. Low-maintenance and resilient, red valerian is perfect for xeriscapes, rock gardens, and along ",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
      waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
      waterRequirement: "Low Water",
      hardinessZones: "4-9",
      matureSize: `20" x 20"`,
    },
 
   
    {
      id: 3,
      name: "Black Eyed Susan",
      scientificName: "Rudbeckia hirta",
      image:
        "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/perennials/Rudbeckia.jpg",
      description:
        "Black-Eyed Susan is a cheerful, resilient perennial that brings bright yellow, daisy-like flowers to New Mexico gardens from summer into fall. Its tough nature makes it well-suited to hot, dry conditions, and it readily attracts bees, butterflies, and other pollinators. With minimal care, it adds bold color to borders, wildflower plantings, and xeriscapes, often naturalizing over time.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
            waterRequirement: "Low Water",
      hardinessZones: "3-9",
      matureSize: `24" x 18"`,
    },
    {
      id: 4,
      name: "Phlox",
      scientificName: "Phlox paniculata",
      image:
        "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/TypesofProducts/phlox-5091730_1920.jpg",
      description:
        "Phlox offers clusters of fragrant, star-shaped flowers that bloom from spring through summer, bringing soft color and pollinators to New Mexico gardens. With good air circulation and moderate watering, phlox can thrive in Albuquerque’s dry climate. It works well in cottage gardens, borders, and mixed beds, providing a lush look when grouped in masses.",
      sunIcon:
        "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
      sunRequirement: "Partial Sun",
      waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Medium-water.png",
      waterRequirement: "Medium Water",
      hardinessZones: "4-8",
      matureSize: `24" x 18"`,
    },
    {
        id: 5,
        name: "Creeping Phlox",
        scientificName: "Phlox subulata",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Xeric/bedding/creeping-phlox-in-the-ozarks-4123341_1920.jpg",
        description: "Creeping Phlox is a low-growing, colorful perennial that thrives in New Mexico’s dry, sunny conditions. Known for its vibrant blooms in shades of pink, purple, and white, Creeping Phlox flowers in spring, adding a burst of color to rock gardens, borders, and slopes. It prefers well-draining soil and full sun, making it an excellent choice for xeriscaping. Drought-tolerant once established, it requires minimal water and works well as a ground cover, spreading quickly to fill in spaces while attracting pollinators.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
        waterRequirement: "Low Water",
        hardinessZones: "3-9",
        matureSize: `6" x 18"`,
        native: false
      },
    

    {
      id: 6,
      name: "Catmint",
      scientificName: "Nepeta spp.",
      image:
        "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/perennials/catmint.jpg",
      description:
        "Catmint is a hardy, drought-tolerant perennial that thrives in New Mexico’s dry climate, producing soft gray-green foliage and spikes of lavender-blue flowers from spring through fall. It attracts pollinators like bees and butterflies, and its aromatic leaves deter deer and rabbits. Low-maintenance and long-blooming, catmint is ideal for borders, pathways, and xeriscapes.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
        waterRequirement: "Low Water",
      hardinessZones: "4-9",
      matureSize: `18" x 24"`,
    },
    {
        id: 7,
        name: "Penstemon",
        scientificName: "Penstemon strictus",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Xeric/bedding/penstemon.jpg",
        description: "Penstemon is a vibrant perennial well-suited to New Mexico’s climate. With tall spikes of tubular flowers in colors ranging from purple to red and pink, Penstemon blooms from spring to summer, attracting hummingbirds and pollinators. It thrives in full sun and well-draining soil, making it an excellent choice for xeriscaping and rock gardens. Drought-tolerant once established, Penstemon requires little water and adds bold color and texture to dry, sunny landscapes.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
        waterRequirement: "Low Water",
        hardinessZones: "3-8",
        matureSize: `24" x 30"`,
        native: false
      },
    
      {
        id: 8,
        name: "Thrift",
        scientificName: "Armeria maritima",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Xeric/bedding/thrift.jpg",
        description: "Thrift is a hardy, compact perennial ideal for New Mexico gardens. Known for its bright, spherical clusters of pink, red, or white flowers, it thrives in well-draining soil and full sun. This low-maintenance plant is drought-tolerant once established, making it a great addition to xeriscaping or coastal-inspired landscapes. With its mounding habit and tolerance for dry conditions, Thrift adds color and texture to rock gardens, borders, or containers.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
        waterRequirement: "Low Water",
        hardinessZones: "3-9",
        matureSize: `8" x 8"`,
        native: false
      },
    {
      id: 9,
      name: "Bee Balm",
      scientificName: "Monarda spp.",
      image:
        "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/perennials/bee-balm-1043110_1920.jpg",
      description:
        "Bee Balm, also known as Monarda, is a fragrant perennial that thrives in New Mexico gardens, attracting bees, butterflies, and hummingbirds. Its showy, tubular flowers bloom in vibrant reds, pinks, and purples, adding color and texture throughout summer. Bee Balm prefers moist, well-drained soil and some afternoon shade, making it a great choice for woodland edges, pollinator gardens, or containers.",
      sunIcon:
        "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
      sunRequirement: "Partial Sun",
      waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Medium-water.png",
      waterRequirement: "Medium Water",
      hardinessZones: "4-9",
      matureSize: `30" x 20"`,
    },
    {
      id: 10,
      name: "Coneflower",
      scientificName: "Echinacea purpurea",
      image:
        "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/perennials/coneflower.jpg",
      description:
        "Coneflower, or Echinacea, is a hardy perennial known for its daisy-like flowers and prominent central cones. Thriving in New Mexico’s hot, dry climate, coneflowers are easy to grow and attract pollinators like bees and butterflies. Their vibrant purple, pink, or white blooms bloom from summer to fall, and once established, they require minimal care, making them perfect for xeriscapes, wildflower gardens, and borders.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
      waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
      waterRequirement: "Low Water",
      hardinessZones: "3-9",
      matureSize: `30" x 20"`,
    },

 
  ],

  droughttolerant: [
    {
        id: 12,
        name: "Golden Yarrow",
        scientificName: "Eriophyllum confertiflorum",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Xeric/shrubs/yarrow.jpg",
        description: "Golden yarrow is a hardy, drought-tolerant perennial ideal for New Mexico gardens. This low-maintenance plant features clusters of bright yellow flowers that bloom from spring to summer, attracting bees and butterflies. Thriving in full sun and well-draining soil, golden yarrow is perfect for xeriscaping, as it requires minimal water once established. Its soft, silvery-green foliage adds texture and contrast to gardens, making it an excellent choice for low-water landscapes and native plant gardens.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
        waterRequirement: "Low Water",
        hardinessZones: "3-8",
        matureSize: "2' x 2'",
        native: false
      },
      {
        id: 39,
        name: "Mexican Hyssop",
        scientificName: "Agastache mexicana",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Xeric/shrubs/Agastache_rupestre.jpg",
        description: "Mexican hyssop is a vibrant, drought-tolerant perennial that thrives in New Mexico’s dry climate. Known for its clusters of tubular, purple to orange flowers, it attracts hummingbirds and butterflies throughout the summer. This herbaceous plant prefers full sun and well-draining soil, requiring minimal water once established. With its aromatic foliage and ability to tolerate heat, Mexican hyssop is an excellent choice for xeriscaping, pollinator gardens, or adding color and texture to low-water landscapes.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
        waterRequirement: "Low Water",
        hardinessZones: "5-10",
        matureSize: "4' x 2'",
      },
      {
        id: 41,
        name: "Chocolate Flower",
        scientificName: "Berlandiera lyrata",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/perennials/640px-Kaldari_Berlandiera_lyrata_01.jpg",
        description: "Chocolate flower is a low-water, heat-loving perennial native to the Southwest. It produces bright yellow, daisy-like blooms with a rich chocolate scent, especially strong in the morning sun. Blooming from spring through fall, this wildflower is ideal for pollinator gardens and xeriscapes. It thrives in full sun, tolerates poor soils, and requires minimal watering once established—making it perfect for New Mexico landscapes.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
        waterRequirement: "Low Water",
        hardinessZones: "4-10",
        matureSize: "1' x 1'",
      },
      
      {
        id: 13,
        name: "Speedwell",
        scientificName: "Veronica spp.",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Xeric/bedding/speedwel.jpg",
        description: "Speedwell is a versatile perennial that flourishes in New Mexico’s sunny, dry conditions. Known for its spikes of blue, purple, or white flowers, it attracts pollinators and blooms from spring to early summer. Speedwell thrives in well-draining soil and full sun, making it an excellent choice for rock gardens or borders. Drought-tolerant once established, it’s a low-maintenance plant that adds vibrant color to xeriscapes while requiring minimal water.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
        waterRequirement: "Low Water",
        hardinessZones: "3-8",
        matureSize: `18" x 18"`,
        native: false
      },

      {
        id: 14,
        name: "Rockcress",
        scientificName: "Arabis spp.",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Xeric/bedding/golden-rock-cress-7490_1920.jpg",
        description: "Rockcress is a hardy, low-growing perennial perfect for New Mexico gardens. Known for its clusters of small, four-petaled white or pink flowers, Rockcress blooms in early spring, brightening up rock gardens, borders, and slopes. It thrives in full sun and well-draining soil, making it ideal for xeriscaping. Drought-tolerant once established, this low-maintenance plant adds color and texture to dry landscapes while requiring minimal water. Its compact size and ability to spread make it a great choice for ground cover.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
        waterRequirement: "Low Water",
        hardinessZones: "3-8",
        matureSize: `8" x 18"`,
        native: false
      },
    {
        id: 15,
        name: "Snow in Summer",
        scientificName: "Cerastium tomentosum",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Xeric/bedding/snow-in-summer.jpg",
        description: "Snow in Summer is a fast-growing perennial known for its silvery foliage and carpet of small, white flowers that bloom in late spring to early summer. Perfect for New Mexico’s dry climate, it thrives in full sun and well-draining soil, making it an excellent choice for xeriscaping or rock gardens. Snow in Summer is drought-tolerant once established and provides a low-maintenance ground cover that adds both texture and color to dry, sunny landscapes. Its ability to spread makes it ideal for filling in empty spaces in gardens.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
        waterRequirement: "Low Water",
        hardinessZones: "3-7",
        matureSize: `8" x 18"`,
        native: false
      },
    {
      id: 16,
      name: "Meadow Sage",
      scientificName: "Salvia pratensis",
      image:
        "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/perennials/meadow_sage.jpg",
      description:
        "Meadow Sage, or Midnight Salvia, is a hardy perennial known for its spikes of vibrant purple, blue, or pink flowers that bloom in late spring to early summer. This drought-tolerant plant thrives in New Mexico’s sunny, dry climate, attracting pollinators like bees and butterflies. With minimal care, meadow sage adds color and texture to garden beds, borders, and xeriscapes.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
      waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
      waterRequirement: "Low Water",
      hardinessZones: "4-8",
      matureSize: `30" x 18"`,
    },
    {
        id: 17,
        name: "Desert Zinnia",
        scientificName: "Zinnia acerosa",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Xeric/bedding/DesertZinnia_(50619381807).jpg",
        description: "Desert Zinnia is a drought-tolerant perennial native to the southwestern U.S., making it a perfect addition to New Mexico gardens. With its bright, daisy-like flowers in shades of yellow, orange, and pink, Desert Zinnia blooms from spring to fall, attracting pollinators such as bees and butterflies. It thrives in full sun and well-draining soil, requiring minimal water once established. This hardy plant is ideal for xeriscaping, rock gardens, and dry landscapes, adding vibrant color and texture to arid environments.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
        waterRequirement: "Low Water",
        hardinessZones: "6-11",
        matureSize: `12" x 12"`,
        native: false
      },

    {
        id: 18,
        name: "Oriental Poppy",
        scientificName: "Papaver orientale",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Xeric/bedding/oriental-poppy.jpg",
        description: "Oriental Poppy is a striking perennial that thrives in New Mexico's sunny, dry climate. Known for its large, vibrant blooms in shades of red, orange, and pink, it flowers in late spring to early summer, creating a bold statement in the garden. Preferring well-draining soil and full sun, Oriental Poppy is drought-tolerant once established. While it requires minimal water, it benefits from occasional deep watering in hotter months. This plant is ideal for adding a dramatic touch to xeriscapes, borders, or wildflower gardens.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
        waterRequirement: "Low Water",
        hardinessZones: "3-7",
        matureSize: `30" x 20"`,
        native: false
      },
      {
        id: 19,
        name: "Mexican Hat",
        scientificName: "Ratibida columnifera",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Xeric/bedding/flower-1378734_1920.jpg",
        description: "Mexican Hat is a hardy, drought-tolerant perennial native to the southwestern United States, making it a great choice for New Mexico gardens. Known for its striking, daisy-like flowers with red and yellow petals surrounding a conical, brown center, it blooms from summer to fall. Mexican Hat thrives in full sun and well-draining soil, requiring little water once established. Perfect for wildflower meadows, xeriscaping, or native plant gardens, it attracts pollinators while adding a pop of color and texture to dry landscapes.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
        waterRequirement: "Low Water",
        hardinessZones: "3-9",
        matureSize: `22" x 2"`,
        native: false
      },
    {
        id: 20,
        name: "Day Lillies",
        scientificName: "Hemerocallis spp.",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Xeric/bedding/daylily-5286921_1920.jpg",
        description: "Daylilies are hardy perennials that thrive in New Mexico’s sunny, dry conditions. Known for their vibrant, trumpet-shaped flowers in a variety of colors, Daylilies bloom profusely in late spring and summer, with each flower lasting just one day but replaced by others throughout the blooming season. These low-maintenance plants prefer well-draining soil and full sun, making them an excellent choice for xeriscaping and garden borders. Drought-tolerant once established, Daylilies require minimal water and provide long-lasting color to dry, sunny landscapes.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
        waterRequirement: "Low Water",
        hardinessZones: "3-9",
        matureSize: `12" x 12"`,
        native: false
      },
    {
        id: 21,
        name: "Hardy African Daisy",
        scientificName: "Arctotis spp.",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Xeric/bedding/hardy-african-daisy.jpg",
        description: "Hardy African Daisy is a vibrant perennial that thrives in New Mexico’s hot, dry climate. Known for its large, daisy-like flowers in shades of white, orange, and purple, this plant blooms from spring to fall, adding bright color to gardens. It prefers full sun and well-draining soil, making it ideal for xeriscaping or rock gardens. Once established, Hardy African Daisy is drought-tolerant and requires minimal water, making it a perfect low-maintenance choice for dry, sunny landscapes while attracting pollinators.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
        waterRequirement: "Low Water",
        hardinessZones: "9-11",
        matureSize: `10" x 18"`,
        native: false
      },
    {
        id: 22,
        name: "Native Blanket Flowoer",
        scientificName: "Gaillardia pulchella",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Xeric/bedding/indian-blanket-9063340_1920.jpg",
        description: "Native Blanket Flower, also known as Firewheel, is a hardy, drought-tolerant perennial that thrives in New Mexico’s arid climate. With its striking, daisy-like flowers in vibrant red, orange, and yellow, Native Blanket Flower blooms from spring to fall, adding a burst of color to gardens. It prefers full sun and well-draining soil, making it ideal for xeriscaping, wildflower meadows, and rock gardens. Once established, Native Blanket Flower is low-maintenance and requires minimal water, while also attracting pollinators like bees and butterflies.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
        waterRequirement: "Low Water",
        hardinessZones: "2-11",
        matureSize: `18" x 8"`,
        native: false
      },
      {
        id: 60,
        name: "Provence Lavender",
        scientificName: "Lavandula x intermedia 'Provence'",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/perennials/bee-8088407_1280.jpg",
        description: "Provence lavender is a fragrant, drought-tolerant shrub prized for its long spikes of purple flowers and silver-green foliage. Blooming from late spring to early summer, it attracts bees and butterflies while adding a calming scent to the garden. Ideal for xeriscaping in New Mexico, it thrives in full sun and well-drained soils, requiring minimal water once established. Its compact, mounded form makes it suitable for borders, herb gardens, and decorative dry landscapes.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
        waterRequirement: "Low Water",
        hardinessZones: "5-9",
        matureSize: "2' x 2'",
      },
      
    {
        id: 23,
        name: "Chrysanthemum",
        scientificName: "Chrysanthemum spp.",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Xeric/bedding/chrysanthemums-3780098_1920.jpg",
        description: "Chrysanthemum is a popular perennial that brings vibrant fall color to New Mexico gardens. With its wide range of flower shapes and colors, including yellow, red, pink, and purple, Chrysanthemums bloom in late summer to fall, adding a cheerful display to landscapes. They thrive in full sun and well-draining soil, making them ideal for garden beds, borders, and containers. Once established, Chrysanthemums are relatively drought-tolerant, requiring minimal water, and attract pollinators such as bees and butterflies, making them a great addition to xeriscapes.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
        waterRequirement: "Low Water",
        hardinessZones: "3-9",
        matureSize: "2' x 3'",
        native: false
      },
      {
        id: 61,
        name: "New Mexico Primrose",
        scientificName: "Oenothera berlandieri",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/perennials/Oenothera_berlandieri.jpg",
        description: "New Mexico primrose is a tough, drought-tolerant perennial native to the Southwest. It produces bright yellow, cup-shaped flowers that open in the evening and close by midday. The narrow, jagged leaves form a low mat that spreads easily, making it ideal as a groundcover in sunny, dry areas. Well-suited for xeriscaping, this wildflower thrives in full sun and well-drained soil, blooming from spring through fall with minimal water.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
        waterRequirement: "Low Water",
        hardinessZones: "4-9",
        matureSize: `10" x 18"`,
      },
      {
        id: 62,
        name: "Gray Creeping Germander",
        scientificName: "Teucrium aroanium",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/perennials/Teucrium_aroanium_-_San_Luis_Obispo_Botanical_Garden_-_DSC05878.jpg",
        description: "Gray Creeping germander is a low-growing, evergreen shrub that forms a dense mat of silvery-gray, aromatic foliage. It blooms in late spring to early summer with spikes of small, pink to purple flowers that attract pollinators like bees and butterflies. This drought-tolerant plant is perfect for xeriscaping and ground covers in New Mexico, thriving in full sun and well-drained soils. It requires minimal water once established and adds both texture and color to dry, rocky landscapes.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
        waterRequirement: "Low Water",
        hardinessZones: "5-9",
        matureSize: `10" x 12-"`,
      },
      
    {
        id: 24,
        name: "Coreopsis",
        scientificName: "Coreopsis spp.",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Xeric/bedding/coreopsis-2665188_1920.jpg",
        description: "Coreopsis is a hardy, drought-tolerant perennial that thrives in New Mexico's sunny, dry climate. Known for its bright, daisy-like flowers in shades of yellow, pink, and red, Coreopsis blooms from spring to fall, providing long-lasting color to gardens. It prefers well-draining soil and full sun, making it ideal for xeriscaping, wildflower meadows, and borders. Once established, Coreopsis requires minimal water, making it a low-maintenance choice that attracts pollinators while brightening up dry landscapes.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
        waterRequirement: "Low Water",
        hardinessZones: "4-9",
        matureSize: `6" x 12"`,
        native: false
      },
    {
        id: 25,
        name: "Mexican Evening Primrose",
        scientificName: "Oenothera speciosa",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Xeric/bedding/mexican-evening-primrose.jpg",
        description: "Mexican Evening Primrose is a hardy, drought-tolerant perennial perfect for New Mexico gardens. Its pink, cup-shaped flowers bloom from spring to fall, attracting pollinators while thriving in full sun and well-draining soil. Spreading easily by rhizomes, it makes excellent ground cover but can become invasive if unchecked. Ideal for xeriscaping, it requires minimal water once established.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
        waterRequirement: "Low Water",
        hardinessZones: "5-9",
        matureSize: `12" x 2'`,
        native: false
      },
      {
        id: 26,
        name: "Autumn Sage",
        scientificName: "Salvia greggii",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flower/autumn-sage.jpg",
        description: "Autumn Sage is a hardy, drought-tolerant perennial perfect for New Mexico gardens. Blooming from spring to fall, it produces vibrant red, pink, or purple flowers that attract hummingbirds and pollinators. Thriving in full sun and well-drained soil, it requires minimal water once established. Its aromatic foliage and compact growth make it ideal for borders, xeriscapes, or wildlife gardens, adding long-lasting color to the landscape.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
        waterRequirement: "Low Water",
        hardinessZones: "6-9",
        matureSize: "2' x 3'",
      },
      {
        id: 33,
        name: "English Lavendar",
        scientificName: "Lavandula angustifolia",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flower/lavender-4348354_1920.jpg",
        description: "English lavender thrives in New Mexico’s dry, sunny climate, making it a perfect choice for low-water gardens. This fragrant, drought-tolerant herb prefers well-draining soil and full sun, producing purple blooms that attract bees and butterflies. Once established, it requires minimal watering and resists deer and pests. Its aromatic flowers can be used for culinary, medicinal, or decorative purposes, adding both beauty and function to any garden.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
        waterRequirement: "Low Water",
        hardinessZones: "5-9",
        matureSize: "1.5' x 1.5'",
      },
  ],
  shadeloving: [
    {
      id: 27,
      name: "Hostas",
      scientificName: "Hosota spp.",
      image:
        "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/perennials/plantain-lily-2370852_1920.jpg",
      description:
        "Hostas are shade-loving perennials known for their lush, heart-shaped foliage and delicate flowers that bloom in summer. Perfect for New Mexico gardens with dappled or full shade, hostas thrive in cooler, more protected areas of the garden. With minimal care, they provide year-round texture and color, and their flowers attract hummingbirds and bees. Ideal for woodland gardens, borders, or containers.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Cloudy.png",
        sunRequirement: "Full Shade",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Medium-water.png",
        waterRequirement: "Medium Water",
      hardinessZones: "3-9",
      matureSize: `30" x 40"`,
    },
    {
      id: 28,
      name: "Hydrangeas",
      scientificName: "Hydrangea spp.",
      image:
        "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/perennials/hydrangea-2749614_1920.jpg",
      description:
        "Hydrangeas are beloved for their large, showy blooms that come in a range of colors, from pinks and blues to whites and purples. These moisture-loving perennials thrive in New Mexico’s climate when provided with some afternoon shade and regular watering. Hydrangeas add elegance and charm to garden beds, borders, and shaded areas, and their flowers are a favorite for cut arrangements.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Partial Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Medium-water.png",
        waterRequirement: "Medium Water",
      hardinessZones: "4-9",
      matureSize: `60" x 60"`,
    },
    {
        id: 29,
        name: "Columbine",
        scientificName: "Aquilegia spp.",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Xeric/bedding/columbine-7246650_1920.jpg",
        description: "Columbine is a delicate, shade-loving perennial that adds charm to New Mexico gardens. Known for its unique, spurred flowers in shades of red, yellow, purple, and blue, Columbine blooms in spring to early summer, attracting hummingbirds and pollinators. It thrives in well-draining soil and partial to full shade, making it perfect for woodland gardens or shaded borders. While it prefers moderate moisture, Columbine is drought-tolerant once established and adds a beautiful, textured touch to gardens with its graceful, fern-like foliage.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Partial Sun",

        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
        waterRequirement: "Low Water",
        hardinessZones: "3-8",
        matureSize: `24" x 12"`,
        native: false
      },
      {
        id: 30,
        name: "Coral Bells",
        scientificName: "Heuchera spp.",
        image:
          "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/perennials/coral_bells.jpg",
        description:
          "Coral Bells, or Heuchera, bring striking foliage and delicate flower spikes to New Mexico gardens, offering year-round visual interest. Their leaves come in a variety of colors—from deep burgundy to lime green—and their small, bell-shaped blooms attract hummingbirds in late spring to early summer. With some protection from harsh afternoon sun, Coral Bells do well in dry shade areas and make excellent additions to borders, containers, or under trees.",
        sunIcon:
          "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
        sunRequirement: "Partial Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Medium-water.png",
              waterRequirement: "Medium Water",
        hardinessZones: "4-9",
        matureSize: `18" x 24"`,
      },
      {
        id: 31,
        name: "Bleeding Heart",
        scientificName: "Dicentra spp.",
        image:
          "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/perennials/bleeding-heart-4183263_1280.jpg",
        description:
          "Bleeding Heart is a captivating perennial known for its unique, heart-shaped flowers that bloom in shades of pink or white. Perfect for shady, moist spots in your Albuquerque garden, this plant thrives with minimal care and adds a touch of elegance to any landscape. Bleeding Heart grows best in cool, shaded areas, offering dramatic visual appeal with its arching stems and fern-like foliage. It’s ideal for borders, woodland gardens, or shady corners, and its delicate blooms attract hummingbirds and pollinators.",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Cloudy.png",
          sunRequirement: "Full Shade",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Medium-water.png",
              waterRequirement: "Medium Water",
        hardinessZones: "3-9",
        matureSize: `24" x 18"`,
      },
      {
        id: 32,
        name: "Lamium",
        scientificName: "Lamium maculatum",
        image:
          "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/perennials/lamium.jpg",
        description:
          "Lamium, also known as spotted dead-nettle, is a versatile and low-growing perennial that thrives in shaded areas. Its attractive variegated foliage and small flowers in shades of purple, pink, or white make it an excellent ground cover for shaded spots in your garden. Lamium is perfect for adding texture and color to the front of garden beds, rock gardens, or as a filler between taller plants. It’s an easy-to-care-for plant that flourishes in well-drained, moist soil and is great for attracting pollinators.",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Cloudy.png",
          sunRequirement: "Full Shade",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Medium-water.png",
              waterRequirement: "Medium Water",
        hardinessZones: "4-9",
        matureSize: `10" x 16"`,
      },

  ],
};

export default perennialdata;
