import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { Raleway } from 'next/font/google';


const raleway = Raleway({
  subsets: ['latin'],
  weight: ['400', '700'], // Optional: specify weights you want
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Jericho Nursery</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />       
      </Head>
      <div className={`${styles.page} ${styles.raleway}`}>
        <h1>hello world</h1>
       
      </div>
    </>
  );
}
